import 'package:auto_route/auto_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter_markdown_selectionarea/flutter_markdown_selectionarea.dart';

const disclaimer = '''# DISCLAIMER
**Last updated: December 07, 2024**  

---

## PLATFORM DISCLAIMER  
**Kernvind** ("we," "us," or "our") provides a platform that allows users to create AI-powered bots and integrate their own large language models (LLMs) and data sources, such as YouTube transcripts and Google Drive files, to interact with and extract insights from unstructured datasets. These data sources are owned by the user, and Kernvind does not claim ownership or control over them. The services and tools provided through [https://www.kernvind.com](https://www.kernvind.com) (the "Site") and our mobile application are designed to facilitate these processes.  

All content and tools available on the Site and our mobile application are provided in good faith. However, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or functionality provided by the platform.  

**UNDER NO CIRCUMSTANCES SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF USING THE SITE, OUR MOBILE APPLICATION, OR ANY TOOLS OR SERVICES PROVIDED THROUGH THEM. YOUR USE OF THE SITE, OUR MOBILE APPLICATION, AND THESE SERVICES IS SOLELY AT YOUR OWN RISK.**  

---

## USE OF THIRD-PARTY SERVICES DISCLAIMER  
Kernvind enables integration with third-party services, including but not limited to ChatGPT, Ollama, and ngrok. These services are provided by external entities and are subject to their own terms, conditions, and policies. We do not have control over these services and make no guarantees or representations regarding their accuracy, performance, availability, or security.  

- **ChatGPT and Ollama**: The use of these AI services may require additional setup, such as acquiring API keys or installing software locally. Users are responsible for ensuring compliance with the respective provider's terms of use and verifying that their hardware meets the necessary requirements (e.g., sufficient computational power or a GPU for Ollama). Additionally, any costs associated with using these third-party services, including API usage or local setup, are the responsibility of the user.  

- **ngrok**: ngrok is a third-party service used for exposing local servers. Users are responsible for configuring ngrok securely, ensuring the security of data exposed via ngrok, and monitoring its usage to prevent unauthorized access or data exposure. Any fees or charges related to ngrok's usage are the user's responsibility.  

**WE DISCLAIM ANY LIABILITY FOR ISSUES ARISING FROM THE USE OF THESE THIRD-PARTY SERVICES. YOUR INTERACTIONS WITH THEM ARE AT YOUR OWN RISK. USERS ARE RESPONSIBLE FOR ANY CHARGES ASSOCIATED WITH THIRD-PARTY SERVICES AND FOR MAINTAINING THE SECURITY OF THEIR SERVICES AND DATA WHILE USING NGROK.**

---

## USER-PROVIDED LLM DISCLAIMER  
The LLMs (Large Language Models) and data that users integrate into Kernvind may not always provide fully accurate or reliable information. As these models are dependent on the input and data provided by the user, there is a possibility that they may generate incorrect or incomplete responses.  

**Kernvind IS NOT RESPONSIBLE FOR THE ACCURACY OR COMPLETENESS OF THE INFORMATION GENERATED BY USER-PROVIDED LLMs AND DATA SOURCES. USERS ARE ADVISED TO VERIFY THE RESULTS AND USE THE PLATFORM AT THEIR OWN RISK.**

---

## EXTERNAL LINKS DISCLAIMER  
The Site and our mobile application may contain (or you may be sent through the Site or our mobile application) links to other websites or content belonging to or originating from third parties, or links to websites and features in banners or other advertising. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us.  

**WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE OR ANY WEBSITE OR FEATURE LINKED IN ANY BANNER OR OTHER ADVERTISING. WE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.**
 
 ---

## **Beta Release Disclaimer**

By using this beta version of Kernvind, you acknowledge and agree to the following:

### **Beta Status**
- The Kernvind Beta is a pre-release version that may contain bugs or incomplete features. 
- It is provided "as-is" for testing purposes only. While we strive to provide the best experience, support may be limited, and stability is not guaranteed during this phase.

### **Limited Features and Support**
- Some features may be incomplete or not fully functional. 
- Users may experience errors, downtime, or changes to features as we continue to develop the app.

### **Feedback and Improvements**
- We encourage beta users to provide feedback and suggestions to help improve the app.
- By using Kernvind, you agree to share your feedback, which may be used to enhance the product.

### **No Guarantee of Stability**
- The beta release may not be as stable as the final version.
- Users may encounter unexpected bugs, crashes, or other issues during this phase.

### **User Responsibility**
- Users are responsible for backing up any data used within the app. 
- Kernvind is not liable for any loss of data or issues resulting from the use of the beta release.
- It is recommended to avoid using sensitive or confidential data during this phase.

### **Liability Disclaimer**
- Kernvind disclaims all liability for any potential issues that may arise during the beta phase. 
- The app is provided "as-is" for testing purposes only.

### **Free Access and Future Subscription Plans**
- Currently, the Kernvind Beta is available free of charge.
- However, please note that in the future, subscription plans will be required to continue using Kernvind.

### **Data Deletion**
- At the conclusion of the beta phase, user data may be deleted, and a fresh start may be initiated for the final version of Kernvind.
- Users are encouraged to back up any important data before the end of the beta phase, as Kernvind may not retain any information from beta users.

''';

@RoutePage()
class DisclaimerPage extends StatelessWidget {
  const DisclaimerPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Kernvind Disclaimer'),
        centerTitle: true,
      ),
      body: Container(
        padding: const EdgeInsets.all(20),
        child: const Center(
          child: SingleChildScrollView(
            child: SelectionArea(
              child: MarkdownBody(
                data: disclaimer,
                //shrinkWrap: true,
                //physics: const NeverScrollableScrollPhysics(),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
